[[main]]
  name = "文档"
  pageRef = "/docs"
  weight = 10

[[main]]
  name = "快速开始"
  pageRef = "/docs/getting-started"
  weight = 20

[[main]]
  name = "用户案例"
  pageRef = "/users"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40
