[[main]]
  name = "文档"
  pageRef = "/docs"
  weight = 10

[[main]]
  name = "简码"
  pageRef = "/docs/shortcodes"
  weight = 20

[[main]]
  name = "用户列表"
  pageRef = "/users"
  weight = 30

[[main]]
  name = "周边"
  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
  weight = 40
